# -*- coding: utf-8 -*-
"""flow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXWyd-mqYT2inLzaB100mZpM8n20p9lI
"""

import tensorflow as tf
import numpy as np

string = tf.Variable('this is a string', tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

rank1_tensor = tf.Variable(['Test', 'Ok', 'Ra'], tf.string)
rank2_tensor = tf.Variable([['test', 'ok', 'yes'], ['test', 'yes', 'ok'], ['ki', 'ra', 'test']], tf.string)

tf.rank(rank2_tensor)

rank2_tensor.shape

tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3, -1])

print(tensor1)
print(tensor2)
print(tensor3)

with tf.Session() as sess:
  tensor.eval()

