# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18KQBo8GJUTxwTBgn_q0Yw_ZLAc3q6l-C
"""

import tensorflow as tf
print(tf.version)

t = tf.zeros([5,5,5,5])
print(t)

t = tf.reshape(t, [625])
print(t)

t = tf.reshape(t, [125, -1])
print(t)

